<?php
 $title = 'News';
 $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
	<div class='col-md-2'>
		<?php echo $this->sidebar 
		?>
	</div>
	<div class='col-md-9 col-md-offset-1'>
	<table>
		<?php foreach ($this->paginator as $newses) : ?>
		<table>
		<tr>
			<p><th><?php echo $this->escapeHtml($newses->title);?></p>
		</tr>
		<tr>
			<p><td><?php echo $this->escapeHtml($newses->date . ',');?>
			theme_id&nbsp;<?php echo $this->escapeHtml($newses->theme_id);?></td></p>
		</tr>
		<tr>
			<td><?php /*echo $this->escapeHtml($newses->text);*/
			echo $this->escapeHtml(mb_substr($newses->text , 0 , 256)) . '...';?>
			<p align="right"><a href="<?php echo $this->url('newses',
            array('action'=>'NewsByID', 'id' => $newses->news_id));?>">read more</a></p>
			</td>
		</tr>
		<br></br>
		<?php endforeach; ?>
	</table>
	
	<?php
	echo $this->paginationControl(
		// the paginator object
		$this->paginator,
		// the scrolling style
		'sliding',
		// the partial to use to render the control
		'partial/paginator.phtml',
		// the route to link to when a user clicks a control link
		array(
        'route' => 'newses'
		)
	);
	?>
	</div>
</div>



